In [1]:
import numpy as np

In [2]:
A=np.matrix([[1,2,1],[1,1,3],[1,4,2]])
print(A)

[[1 2 1]
 [1 1 3]
 [1 4 2]]


In [15]:
b=np.matrix([[4],[10],[7]])
print(b)

[[ 4]
 [10]
 [ 7]]


In [16]:
Ainv=np.linalg.inv(A)
print(Ainv)

[[ 2.   0.  -1. ]
 [-0.2 -0.2  0.4]
 [-0.6  0.4  0.2]]


In [17]:
x=Ainv*b
print(x)

[[1.0000000e+00]
 [4.4408921e-16]
 [3.0000000e+00]]


In [18]:
x=np.linalg.solve(A,b)
print(x)

[[1.]
 [0.]
 [3.]]


In [19]:
print(A*x)

[[ 4.]
 [10.]
 [ 7.]]


In [46]:
A=np.loadtxt('Amatrix.txt')
print(A)
A.shape

[[-0.95195327 -0.00861646 -0.69301523  0.6446576  -0.57685875  1.04008   ]
 [ 0.257949   -0.01461396 -0.68491079 -1.0888329   0.82518905 -0.24440684]
 [ 1.1981972   0.21708766  0.93260276 -1.6984745   1.6131042  -1.4850667 ]
 [ 1.1089668   0.18019073 -1.208551   -1.2903596   1.2159222  -0.35617863]
 [-1.6126667  -0.52051641 -0.3607855   0.54562674  1.6139113   0.35452356]
 [-0.35662964 -0.23958191 -1.1823695   2.1353495  -0.5999388   1.8349129 ]]


(6, 6)

In [47]:
b=np.loadtxt('bvektor.txt')
print(b)

[ 0.89769247  0.2523023   0.98402784 -0.51456092 -1.3106536  -0.68731566]


In [48]:
b=np.transpose(np.matrix(b))
print(b)

[[ 0.89769247]
 [ 0.2523023 ]
 [ 0.98402784]
 [-0.51456092]
 [-1.3106536 ]
 [-0.68731566]]


In [51]:
x=np.linalg.solve(A,b)
print(x)

[[ 0.2762938 ]
 [ 1.08482576]
 [ 2.53665861]
 [-2.60797612]
 [ 0.25773438]
 [ 4.57458044]]


In [52]:
print(A*x)

[[ 0.89769247]
 [ 0.2523023 ]
 [ 0.98402784]
 [-0.51456092]
 [-1.3106536 ]
 [-0.68731566]]
