In [ ]:
import numpy as np

Nun können wir die Bibliothek numpy mit der Abkürzung np nutzen.
Wir definieren eine Matrix A und lassen Sie anzeigen

In [14]:
A=np.matrix([[1,2,1],[1,1,3],[1,4,2]])
print(A)

[[1 2 1]
 [1 1 3]
 [1 4 2]]


nun einen Vektor b

In [15]:
b=np.matrix([[4],[10],[7]])
print(b)

[[ 4]
 [10]
 [ 7]]


Wir wollen nun das LGS Ax=b loesen. Erste Moeglichkeit: inverse Matrix berechnen und mit dieser x berechnen:

In [18]:
Ainv=np.linalg.inv(A)
print(Ainv)

[[ 2.   0.  -1. ]
 [-0.2 -0.2  0.4]
 [-0.6  0.4  0.2]]


In [19]:
x=Ainv*b
print(x)

[[1.0000000e+00]
 [4.4408921e-16]
 [3.0000000e+00]]


Sieht komisch aus, ist aber richtig. e-16 heiszt mal 10 hoch -16. Der zweite Eintrag ist also so gut wie 0. Bestimmt ist er sogar exakt 0 und der Rest ist Rundungsfehler. Probe:

In [21]:
print(A*x)

[[ 4.]
 [10.]
 [ 7.]]


Nun zweite Moeglichkeit mit dem solve Befehl. Dieser ist der aufwendigen Inversenberechnung meist vorzuziehen. Hier koennte sich z.B. das numerische Gaussverfahren hinter verstecken. Wahrscheinlich aber noch etwas cleverer, als wir es kennengelernt haben... 

In [ ]:
x=np.linalg.solve(A,b)
print(x)

In [ ]:
print(A*x)

Passt!

Nun lesen wir mal eine Matrix A und einen Vektor A aus  Textfiles ein. Diese Textfiles könnten zum Beispiel Messdaten enthalten. Wir koennten hier prinzpiell auch viel mehr Daten also groeszere A und b einlesen. Auch 1000x1000 waere kein Problem, aber hier lassen wir es mal bei 6x6.

In [23]:
A=np.loadtxt('Amatrix.txt')
print(A)
A.shape

[[-0.95195327 -0.00861646 -0.69301523  0.6446576  -0.57685875  1.04008   ]
 [ 0.257949   -0.01461396 -0.68491079 -1.0888329   0.82518905 -0.24440684]
 [ 1.1981972   0.21708766  0.93260276 -1.6984745   1.6131042  -1.4850667 ]
 [ 1.1089668   0.18019073 -1.208551   -1.2903596   1.2159222  -0.35617863]
 [-1.6126667  -0.52051641 -0.3607855   0.54562674  1.6139113   0.35452356]
 [-0.35662964 -0.23958191 -1.1823695   2.1353495  -0.5999388   1.8349129 ]]


(6, 6)

In [24]:
b=np.loadtxt('bvektor.txt')
print(b)

[ 0.89769247  0.2523023   0.98402784 -0.51456092 -1.3106536  -0.68731566]


In [25]:
b=np.transpose(np.matrix(b))
print(b)

[[ 0.89769247]
 [ 0.2523023 ]
 [ 0.98402784]
 [-0.51456092]
 [-1.3106536 ]
 [-0.68731566]]


In [26]:
x=np.linalg.solve(A,b)
print(x)

[[ 0.2762938 ]
 [ 1.08482576]
 [ 2.53665861]
 [-2.60797612]
 [ 0.25773438]
 [ 4.57458044]]


In [27]:
print(A*x)

[[ 0.89769247]
 [ 0.2523023 ]
 [ 0.98402784]
 [-0.51456092]
 [-1.3106536 ]
 [-0.68731566]]
